language: node_js
node_js:
- "stable"
install: npm install
services:
- postgresql
env:
- TEST_DB_USER=postgres TEST_DB_PASSWORD= TEST_DB_NAME=travis_ci_test
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script: npm test
after_success: npm run coverage

