language: node_js
node_js:
- "stable"
install: npm install
services:
- postgresql
env:
- TEST_DB_USER=test_user TEST_DB_PASSWORD=password TEST_DB_NAME=test_db
before_script:
- psql -c 'create database test_db;' -U postgres
- psql -c "CREATE USER test_user WITH PASSWORD 'password';" -U postgres
script: npm test
after_success: npm run coverage

