version: '3'

services: 
  app:
    container_name: core_app
    build: 
      context: ../..
      dockerfile: ./.docker/dev/Dockerfile
    env_file: 
      - ./.dev.env
    ports: 
      - '3000:3000'
    links: 
      - db
    depends_on: 
      - db
    volumes:
      - /var/www/node_modules
      - ../../logs:/var/lib/logs
    networks:
      - backend
    hostname: app_core
  
  db:
    container_name: database
    image: postgres:9.6-alpine
    ports:
      - '5432:5432'
    env_file: 
      - ./.dev.env
    networks: 
      - backend
    volumes: 
      - codelify-data:/var/lib/postgresql/data

networks: 
  backend:
    driver: bridge
volumes:
  codelify-data:
